apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: fake-service
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: fake-service
  targetNamespace: fake-service
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: fake-service
      namespace: fake-service
  timeout: 2m
