apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fake-service
  namespace: fake-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: fake-service.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fake-service
            port:
              number: 8000
