apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fake-service

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - servicemonitor.yaml

images:
  - name: fake-service
    newTag: latest

commonLabels:
  app.kubernetes.io/name: fake-service
  app.kubernetes.io/managed-by: flux

configMapGenerator:
  - name: fake-service-config
    literals:
      - LOG_LEVEL=INFO
