apiVersion: v1
kind: Service
metadata:
  name: fake-service
  namespace: fake-service
  labels:
    app: fake-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: fake-service
---
apiVersion: v1
kind: Service
metadata:
  name: fake-service-metrics
  namespace: fake-service
  labels:
    app: fake-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: metrics
  selector:
    app: fake-service
